name: Node.js CD (Otomatik Dağıtım)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sunucuya Bağlan ve Güncelle
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Klasöre git ve SSH anahtarını tanıması için bir ayar ekle
            mkdir -p /var/www/cengizdev
            cd /var/www/cengizdev
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts

            # 2. Git işlemi (SSH Linki ile)
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone git@github.com:omercngiz/digitalocean.git .
            fi

            # 3. Senin verdiğin tam yolları kullanarak çalıştır
            /root/.nvm/versions/node/v24.14.0/bin/npm install
            /root/.nvm/versions/node/v24.14.0/bin/pm2 delete cengizdev-app || true
            /root/.nvm/versions/node/v24.14.0/bin/pm2 start app.js --name "cengizdev-app"
            /root/.nvm/versions/node/v24.14.0/bin/pm2 save